---

- name: install systemd
  pacman:
    name: systemd
    state: present
  always_run: yes

- name: configure systemd-journald
  template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd-journald
